image: gradle:7.6.0-jdk19-alpine

stages:
  - build
  - test

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

before_script:
  - chmod +x gradlew

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

build:
  stage: build
  script:
    - ./gradlew build

test:
  stage: test
  script:
    - ./gradlew test jacocoTestCoverageVerification integrationTest
  only:
    - dev
    - main
  artifacts:
    paths:
      - build/reports/tests/test
      - build/reports/tests/integrationTest
      - build/reports/jacoco/test/html/
