image: gradle:7.6.0-jdk19-alpine

stages:
  - build
  - static_analysis
  - test

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

before_script:
  - chmod +x gradlew

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

build:
  stage: build
  script:
    - ./gradlew build

static_analysis:
  stage: static_analysis
  script:
    - ./gradlew checkstyleMain checkstyleTest
  allow_failure: false

test:
  stage: test
  script:
    - ./gradlew test
    - |
      if [[ "$CI_COMMIT_BRANCH" == "main" || "$CI_COMMIT_BRANCH" == "dev" ]]; then
        ./gradlew jacocoTestCoverageVerification
      fi
  artifacts:
    paths:
      - build/reports/jacoco/test/html/