image: gradle:7.6.0-jdk19-alpine

stages:
  - build_and_test
  - code_coverage_check

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

before_script:
  - chmod +x gradlew

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

build_and_test:
  stage: build_and_test
  script:
    - ./gradlew build
    - ./gradlew test

code_coverage_check:
  stage: code_coverage_check
  only:
    - main
    - dev
  script:
    - ./gradlew jacocoTestReport
    - ./gradlew jacocoTestCoverageVerification

  artifacts:
    paths:
      - build/reports/jacoco/test/html/
